[package]
name = "one-billion-row-challange"
version = "0.1.0"
edition = "2024"
default-run = "one-billion-row-challange"

[[bin]]
name = "generate"
path = "src/generate.rs"

[dependencies]
memmap2 = "0.9.10"
rand = "0.8.0"
rustc-hash = "2.1.2"

[profile.release]
debug = true
panic = "abort"
lto = "fat"
incremental = true
