use rand::{distributions::Uniform, prelude::Distribution, seq::SliceRandom};
use std::{fs::File, io::Write, ops::Range, time::Instant};

const OUTPUT_PATH: &str = "data/weather-measurements.csv";
const OUTPUT_DIR: &str = "data";
const MEASUREMENT_COUNT: usize = 10_000_000;
const BATCH_SIZE: usize = 10_000;
const AVERAGE_LINE_SIZE: f64 = 14.35419525743501;
const ESTIMATED_FILE_SIZE: u64 = (AVERAGE_LINE_SIZE * MEASUREMENT_COUNT as f64) as u64;
const ESTIMATED_BATCH_SIZE: usize = (AVERAGE_LINE_SIZE * BATCH_SIZE as f64) as usize;
const TEMPERATURE_RANGE: Range<f64> = -49.9..49.9;
const WEATHER_STATIONS: &[&str] = &[
    "Abha",
    "Abidjan",
    "Abéché",
    "Accra",
    "Addis Ababa",
    "Adelaide",
    "Aden",
    "Ahvaz",
    "Albuquerque",
    "Alexandra",
    "Alexandria",
    "Algiers",
    "Alice Springs",
    "Almaty",
    "Amsterdam",
    "Anadyr",
    "Anchorage",
    "Andorra la Vella",
    "Ankara",
    "Antananarivo",
    "Antsiranana",
    "Arkhangelsk",
    "Ashgabat",
    "Asmara",
    "Assab",
    "Astana",
    "Athens",
    "Atlanta",
    "Auckland",
    "Austin",
    "Baghdad",
    "Baguio",
    "Baku",
    "Baltimore",
    "Bamako",
    "Bangkok",
    "Bangui",
    "Banjul",
    "Barcelona",
    "Bata",
    "Batumi",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Belize City",
    "Benghazi",
    "Bergen",
    "Berlin",
    "Bilbao",
    "Birao",
    "Bishkek",
    "Bissau",
    "Blantyre",
    "Bloemfontein",
    "Boise",
    "Bordeaux",
    "Bosaso",
    "Boston",
    "Bouaké",
    "Bratislava",
    "Brazzaville",
    "Bridgetown",
    "Brisbane",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Bujumbura",
    "Bulawayo",
    "Burnie",
    "Busan",
    "Cabo San Lucas",
    "Cairns",
    "Cairo",
    "Calgary",
    "Canberra",
    "Cape Town",
    "Changsha",
    "Charlotte",
    "Chiang Mai",
    "Chicago",
    "Chihuahua",
    "Chittagong",
    "Chișinău",
    "Chongqing",
    "Christchurch",
    "City of San Marino",
    "Colombo",
    "Columbus",
    "Conakry",
    "Copenhagen",
    "Cotonou",
    "Cracow",
    "Da Lat",
    "Da Nang",
    "Dakar",
    "Dallas",
    "Damascus",
    "Dampier",
    "Dar es Salaam",
    "Darwin",
    "Denpasar",
    "Denver",
    "Detroit",
    "Dhaka",
    "Dikson",
    "Dili",
    "Djibouti",
    "Dodoma",
    "Dolisie",
    "Douala",
    "Dubai",
    "Dublin",
    "Dunedin",
    "Durban",
    "Dushanbe",
    "Edinburgh",
    "Edmonton",
    "El Paso",
    "Entebbe",
    "Erbil",
    "Erzurum",
    "Fairbanks",
    "Fianarantsoa",
    "Flores,  Petén",
    "Frankfurt",
    "Fresno",
    "Fukuoka",
    "Gaborone",
    "Gabès",
    "Gagnoa",
    "Gangtok",
    "Garissa",
    "Garoua",
    "George Town",
    "Ghanzi",
    "Gjoa Haven",
    "Guadalajara",
    "Guangzhou",
    "Guatemala City",
    "Halifax",
    "Hamburg",
    "Hamilton",
    "Hanga Roa",
    "Hanoi",
    "Harare",
    "Harbin",
    "Hargeisa",
    "Hat Yai",
    "Havana",
    "Helsinki",
    "Heraklion",
    "Hiroshima",
    "Ho Chi Minh City",
    "Hobart",
    "Hong Kong",
    "Honiara",
    "Honolulu",
    "Houston",
    "Ifrane",
    "Indianapolis",
    "Iqaluit",
    "Irkutsk",
    "Istanbul",
    "Jacksonville",
    "Jakarta",
    "Jayapura",
    "Jerusalem",
    "Johannesburg",
    "Jos",
    "Juba",
    "Kabul",
    "Kampala",
    "Kandi",
    "Kankan",
    "Kano",
    "Kansas City",
    "Karachi",
    "Karonga",
    "Kathmandu",
    "Khartoum",
    "Kingston",
    "Kinshasa",
    "Kolkata",
    "Kuala Lumpur",
    "Kumasi",
    "Kunming",
    "Kuopio",
    "Kuwait City",
    "Kyiv",
    "Kyoto",
    "La Ceiba",
    "La Paz",
    "Lagos",
    "Lahore",
    "Lake Havasu City",
    "Lake Tekapo",
    "Las Palmas de Gran Canaria",
    "Las Vegas",
    "Launceston",
    "Lhasa",
    "Libreville",
    "Lisbon",
    "Livingstone",
    "Ljubljana",
    "Lodwar",
    "Lomé",
    "London",
    "Los Angeles",
    "Louisville",
    "Luanda",
    "Lubumbashi",
    "Lusaka",
    "Luxembourg City",
    "Lviv",
    "Lyon",
    "Madrid",
    "Mahajanga",
    "Makassar",
    "Makurdi",
    "Malabo",
    "Malé",
    "Managua",
    "Manama",
    "Mandalay",
    "Mango",
    "Manila",
    "Maputo",
    "Marrakesh",
    "Marseille",
    "Maun",
    "Medan",
    "Mek'ele",
    "Melbourne",
    "Memphis",
    "Mexicali",
    "Mexico City",
    "Miami",
    "Milan",
    "Milwaukee",
    "Minneapolis",
    "Minsk",
    "Mogadishu",
    "Mombasa",
    "Monaco",
    "Moncton",
    "Monterrey",
    "Montreal",
    "Moscow",
    "Mumbai",
    "Murmansk",
    "Muscat",
    "Mzuzu",
    "N'Djamena",
    "Naha",
    "Nairobi",
    "Nakhon Ratchasima",
    "Napier",
    "Napoli",
    "Nashville",
    "Nassau",
    "Ndola",
    "New Delhi",
    "New Orleans",
    "New York City",
    "Ngaoundéré",
    "Niamey",
    "Nicosia",
    "Niigata",
    "Nouadhibou",
    "Nouakchott",
    "Novosibirsk",
    "Nuuk",
    "Odesa",
    "Odienné",
    "Oklahoma City",
    "Omaha",
    "Oranjestad",
    "Oslo",
    "Ottawa",
    "Ouagadougou",
    "Ouahigouya",
    "Ouarzazate",
    "Oulu",
    "Palembang",
    "Palermo",
    "Palm Springs",
    "Palmerston North",
    "Panama City",
    "Parakou",
    "Paris",
    "Perth",
    "Petropavlovsk-Kamchatsky",
    "Philadelphia",
    "Phnom Penh",
    "Phoenix",
    "Pittsburgh",
    "Podgorica",
    "Pointe-Noire",
    "Pontianak",
    "Port Moresby",
    "Port Sudan",
    "Port Vila",
    "Port-Gentil",
    "Portland (OR)",
    "Porto",
    "Prague",
    "Praia",
    "Pretoria",
    "Pyongyang",
    "Rabat",
    "Rangpur",
    "Reggane",
    "Reykjavík",
    "Riga",
    "Riyadh",
    "Rome",
    "Roseau",
    "Rostov-on-Don",
    "Sacramento",
    "Saint Petersburg",
    "Saint-Pierre",
    "Salt Lake City",
    "San Antonio",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San José",
    "San Juan",
    "San Salvador",
    "Sana'a",
    "Santo Domingo",
    "Sapporo",
    "Sarajevo",
    "Saskatoon",
    "Seattle",
    "Seoul",
    "Seville",
    "Shanghai",
    "Singapore",
    "Skopje",
    "Sochi",
    "Sofia",
    "Sokoto",
    "Split",
    "St. John's",
    "St. Louis",
    "Stockholm",
    "Surabaya",
    "Suva",
    "Suwałki",
    "Sydney",
    "Ségou",
    "Tabora",
    "Tabriz",
    "Taipei",
    "Tallinn",
    "Tamale",
    "Tamanrasset",
    "Tampa",
    "Tashkent",
    "Tauranga",
    "Tbilisi",
    "Tegucigalpa",
    "Tehran",
    "Tel Aviv",
    "Thessaloniki",
    "Thiès",
    "Tijuana",
    "Timbuktu",
    "Tirana",
    "Toamasina",
    "Tokyo",
    "Toliara",
    "Toluca",
    "Toronto",
    "Tripoli",
    "Tromsø",
    "Tucson",
    "Tunis",
    "Ulaanbaatar",
    "Upington",
    "Vaduz",
    "Valencia",
    "Valletta",
    "Vancouver",
    "Veracruz",
    "Vienna",
    "Vientiane",
    "Villahermosa",
    "Vilnius",
    "Virginia Beach",
    "Vladivostok",
    "Warsaw",
    "Washington, D.C.",
    "Wau",
    "Wellington",
    "Whitehorse",
    "Wichita",
    "Willemstad",
    "Winnipeg",
    "Wrocław",
    "Xi'an",
    "Yakutsk",
    "Yangon",
    "Yaoundé",
    "Yellowknife",
    "Yerevan",
    "Yinchuan",
    "Zagreb",
    "Zanzibar City",
    "Zürich",
    "Ürümqi",
    "İzmir",
];

fn format_size(bytes: u64) -> String {
    let units = ["B", "KB", "MB", "GB"];
    let mut bytes = bytes as f64;

    let mut unit_index = 0;
    while bytes >= 1000.0 && unit_index < units.len() - 1 {
        bytes /= 1000.0;
        unit_index += 1;
    }
    format!("{:.1}{}", bytes, units[unit_index])
}

fn format_time(seconds: f64) -> String {
    if seconds < 60.0 {
        format!("{:.3} seconds", seconds)
    } else if seconds < 3600.0 {
        let minutes = (seconds / 60.0) as u64;
        let remaining_seconds = (seconds % 60.0) as u64;
        format!("{} minutes {} seconds", minutes, remaining_seconds)
    } else {
        let hours = (seconds / 3600.0) as u64;
        let remainder = seconds % 3600.0;
        let minutes = (remainder / 60.0) as u64;
        let remaining_seconds = (remainder % 60.0) as u64;

        if minutes == 0 {
            format!("{} hours {} seconds", hours, remaining_seconds)
        } else {
            format!(
                "{} hours {} minutes {} seconds",
                hours, minutes, remaining_seconds
            )
        }
    }
}

fn main() {
    const { assert!(BATCH_SIZE <= MEASUREMENT_COUNT) };

    println!("Estimated file size: {}", format_size(ESTIMATED_FILE_SIZE));
    println!("Generating data...");
    let begin = Instant::now();

    std::fs::create_dir_all(OUTPUT_DIR).unwrap();
    let mut file = File::create(OUTPUT_PATH).unwrap();
    let mut rng = rand::thread_rng();
    let uniform = Uniform::from(TEMPERATURE_RANGE);

    for n in 0..MEASUREMENT_COUNT / BATCH_SIZE {
        let mut batch = String::with_capacity(ESTIMATED_BATCH_SIZE);
        for m in 0..BATCH_SIZE {
            let station = WEATHER_STATIONS.choose(&mut rng).unwrap();
            let temperature = uniform.sample(&mut rng);
            batch.push_str(&format!("{station};{temperature:.1}\n"));

            let iter = n * BATCH_SIZE + m;
            if iter.is_multiple_of(1000) {
                let progress = 1 + (100 * iter / MEASUREMENT_COUNT);
                let bars = "=".repeat(progress / 2);
                print!("\r[{bars:<50}] {progress}%");
            }
        }
        let _ = write!(file, "{batch}");
    }
    println!();

    let elapsed_time = Instant::now().duration_since(begin).as_secs_f64();
    let file_size = std::fs::metadata(OUTPUT_PATH).unwrap().len();

    println!("Test data successfully written to {OUTPUT_PATH}");
    println!("Actual file size:  {}", format_size(file_size));
    println!("Elapsed time: {}", format_time(elapsed_time));
}
